README add select bindParam example
IBM/nodejs-idb-pconnector pull request #101
Opened 2020-10-07 16:58 UTC by jhonnattan123

2020-10-08 19:23 UTC, abmusse requested changes
The changes overall look good.

Before this can be merged though need to pass the [DCO check](https://github.com/IBM/nodejs-idb-pconnector/pull/101/checks?check_run_id=1221730828)

Also we use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#examples) for commit messages. Consider updating the commit message to something like: 

`docs: Add select prepare, bind, execute example`

2020-10-08 19:29 UTC, jhonnattan123 reviewed
docs: Add select bindParam example

2020-10-08 20:16 UTC, jhonnattan123 commented
> The changes overall look good.
> 
> Before this can be merged though need to pass the [DCO check](https://github.com/IBM/nodejs-idb-pconnector/pull/101/checks?check_run_id=1221730828)
> 
> Also we use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#examples) for commit messages. Consider updating the commit message to something like:
> 
> `docs: Add select bindParam example`

is ready

2020-10-14 02:06 UTC, abmusse commented on .github/workflows/stale.yml
> +        exempt-pr-labels: 'keep-open'
![image](https://user-images.githubusercontent.com/33973272/95934917-9a9aef80-0d97-11eb-983d-3dc1c759d408.png)

Hey @jhonnattan123 Look `fix: Make exempt labels plural for stale action (#100)` was committed with this PR.  This changes is already merged in the master branch. Could you drop that commit from your branch. Thanks!

2020-10-14 16:42 UTC, abmusse approved these changes
LGTM

2020-10-14 16:43 UTC, merged